[workspace]
members = ["day01", "day02", "day03", "day04"]
resolver = "2"

[workspace.package]
edition = "2024"
authors = ["Luna Present <code@lunapresent.net>"]

[workspace.dependencies]
color-eyre = "0.6.5"
